In [6]:
import pandas as pd

In [7]:
# Read Dataset
# https://www.nature.com/articles/s41746-020-00372-6
# https://github.com/nshomron/covidpred/tree/master/data
data = pd.read_csv("corona_tested_individuals_ver_006_english.csv")

E:\Program Files\anaconda3\envs\digitalent\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [8]:
data

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-04-30,0,0,0,0,0,negative,None,female,Other
1,2020-04-30,1,0,0,0,0,negative,None,female,Other
2,2020-04-30,0,1,0,0,0,negative,None,male,Other
3,2020-04-30,1,0,0,0,0,negative,None,female,Other
4,2020-04-30,1,0,0,0,0,negative,None,male,Other
...,...,...,...,...,...,...,...,...,...,...
278843,2020-03-11,0,0,0,0,0,negative,None,None,Other
278844,2020-03-11,0,0,0,0,0,negative,None,None,Other
278845,2020-03-11,0,0,0,0,0,positive,None,None,Contact with confirmed
278846,2020-03-11,0,0,0,0,0,other,None,None,Other
278847,2020-03-11,0,0,0,0,0,negative,None,None,Other

In [9]:
data = data.head(1000)

In [13]:
data

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-04-30,0,0,0,0,0,negative,None,female,Other
1,2020-04-30,1,0,0,0,0,negative,None,female,Other
2,2020-04-30,0,1,0,0,0,negative,None,male,Other
3,2020-04-30,1,0,0,0,0,negative,None,female,Other
4,2020-04-30,1,0,0,0,0,negative,None,male,Other
...,...,...,...,...,...,...,...,...,...,...
995,2020-04-30,0,0,0,0,0,negative,None,female,Other
996,2020-04-30,1,0,0,0,0,negative,None,female,Abroad
997,2020-04-30,0,0,0,0,0,negative,None,female,Other
998,2020-04-30,0,0,0,0,0,negative,None,male,Other
999,2020-04-30,0,0,0,0,0,negative,None,female,Other

In [15]:
# New Dataframe
df = pd.DataFrame(columns=['processed_data','diagnosis'])

for index, row in data.iterrows():
    if(row['cough'] == 'None'):
        cough = '2'
    else:
        cough = row['cough']
        
    if(row['fever'] == 'None'):
        fever = '2'
    else:
        fever = row['fever']
        
    if(row['sore_throat'] == 'None'):
        sore_throat = '2'
    else:
        sore_throat = row['sore_throat']
        
    if(row['shortness_of_breath'] == 'None'):
        shortness_of_breath = '2'
    else:
        shortness_of_breath = row['shortness_of_breath']
        
    if(row['head_ache'] == 'None'):
        head_ache = '2'
    else:
        head_ache = row['head_ache']
        
    if(row['age_60_and_above'] == 'Yes'):
        age_60_and_above = '1'
    elif(row['age_60_and_above'] == 'No'):
        age_60_and_above = '0'
    else:
        age_60_and_above = '2'
        
    if(row['gender'] == 'male'):
        gender = '1'
    elif(row['gender'] == 'female'):
        gender = '0'
    else:
        gender = '2'
        
    if(row['test_indication'] == 'Abroad'):
        test_indication = '1'
    elif(row['gender'] == 'Contact with confirmed'):
        test_indication = '0'
    else:
        test_indication = '2' # Other
        
    if(row['corona_result'] == 'positive'):
        corona_result = '1'
    elif(row['corona_result'] == 'negative'):
        corona_result = '0'
    else:
        corona_result = '2'
    
    temp = [cough, fever, sore_throat, shortness_of_breath, head_ache, age_60_and_above, gender, test_indication]
    df = df.append({'processed_data': temp, 'diagnosis': corona_result}, ignore_index=True)

In [19]:
from sklearn.model_selection import train_test_split 
from sklearn import metrics
x_train, x_test, y_train, y_test = train_test_split(df['processed_data'], df['diagnosis'], test_size=0.33, random_state=42)

In [21]:
# Modeling
from sklearn import svm
from sklearn.svm import SVC

model = SVC(C=1.0, kernel='linear', gamma='auto')

# Train Model
# model.fit(df['processed_data'].values.tolist(), df['diagnosis'].values.tolist())
model.fit(x_train.values.tolist(), y_train.values.tolist())

SVC(gamma='auto', kernel='linear')

In [7]:
# Saving Model
import pickle

pkl_filename = "model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

In [25]:
y_pred = model.predict(x_test.values.tolist())
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9727272727272728